/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_appsync_graphqlEndpoint": "https://eggdt5g6zneodbev4g2be4ykpy.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-6ekujn4lirg6zf2qs5zra4rup4",
  "aws_cognito_identity_pool_id": "us-east-1:586b58ca-736b-49fa-831b-b5d1ef7d877a",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_3v4SXXzeH",
  "aws_user_pools_web_client_id": "4k7afbee5abd8tr792f0sgvhi0",
  "oauth": {},
  "aws_cognito_username_attributes": [],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
      "EMAIL",
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
      "SMS",
  ],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 8,
      "passwordPolicyCharacters": [],
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL",
  ],
};


export default awsmobile;
